development:
  strategy: oauth
  oauth_consumer_key: <%= LOCAL_OAUTH_CONSUMER_KEY %>
  oauth_consumer_secret: <%= LOCAL_OAUTH_CONSUMER_SECRET %>
#  base_url: "https://twitter.com"
  base_url: "https://api.twitter.com/1.1"
  authorize_path: "/oauth/authenticate"
  api_timeout: 10
  remember_for: 14 # days
  oauth_callback: "http://localhost:3000/oauth_callback"
test:
  strategy: oauth
  oauth_consumer_key: testkey
  oauth_consumer_secret: testsecret
#  base_url: "https://twitter.com"
  base_url: "https://api.twitter.com/1.1"
  authorize_path: "/oauth/authenticate"
  api_timeout: 10
  remember_for: 14 # days
  oauth_callback: "http://localhost:3000/oauth_callback"
staging:
  strategy: oauth
  oauth_consumer_key: <%= ENV['OAUTH_CONSUMER_KEY'] %>
  oauth_consumer_secret: <%= ENV['OAUTH_CONSUMER_SECRET'] %>
  authorize_path: "/oauth/authenticate"
#  base_url: "https://twitter.com"
  base_url: "https://api.twitter.com/1.1"
  api_timeout: 10
  remember_for: 14 # days
production:
  strategy: oauth
  oauth_consumer_key: <%= ENV['OAUTH_CONSUMER_KEY'] %>
  oauth_consumer_secret: <%= ENV['OAUTH_CONSUMER_SECRET'] %>
  authorize_path: "/oauth/authenticate"
#  base_url: "https://twitter.com"
  base_url: "https://api.twitter.com/1.1"
  api_timeout: 10
  remember_for: 14 # days
